// Every notification the app sends, in English and Spanish. Each template returns
// { subject, lines, cta?, sms? }: lines are paragraphs, cta is the button, sms is the (optional) text message.
// `transactional` messages (receipts, security, booking status) are always sent; the rest respect the user's email preference.

const h = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
export const usd = (c) => "$" + (c / 100).toLocaleString("en-US", { minimumFractionDigits: c % 100 ? 2 : 0, maximumFractionDigits: 2 });
export const longDate = (d, lang) => new Date(d + "T12:00:00Z").toLocaleDateString(lang === "es" ? "es-US" : "en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric", timeZone: "UTC" });

const B = "Bella's Música";

// Event types are stored in English. In Spanish emails they are written as a plain lowercase noun with no article
// ("boda", "cumpleaños"), because the nouns differ in gender: the templates say "tu boda", "su quinceañera", never "un boda".
const ES_EVENTS = { Wedding: "boda", "Quinceañera": "quinceañera", Birthday: "cumpleaños", Anniversary: "aniversario", Serenata: "serenata", "Corporate / Restaurant": "evento corporativo o de restaurante", Other: "evento" };
export const eventLabel = (e, lang) => (lang === "es" ? ES_EVENTS[e] || String(e).toLowerCase() : e);

export const TEMPLATES = {
  "auth.verify": { transactional: true,
    en: (v) => ({ subject: "Confirm your email", lines: [`Hi ${v.name},`, `Welcome to ${B}! Please confirm your email address so we can send you booking updates.`, "This link works for 24 hours. If you didn't create an account, you can ignore this message."], cta: { label: "Confirm my email", url: v.url } }),
    es: (v) => ({ subject: "Confirma tu correo", lines: [`Hola ${v.name},`, `¡Bienvenido a ${B}! Confirma tu correo para que podamos enviarte avisos de tus reservas.`, "Este enlace funciona por 24 horas. Si no creaste una cuenta, ignora este mensaje."], cta: { label: "Confirmar mi correo", url: v.url } }) },

  "auth.reset": { transactional: true,
    en: (v) => ({ subject: "Reset your password", lines: [`Hi ${v.name},`, "Someone asked to reset the password for your account. Tap the button to choose a new one.", "This link works for 1 hour and can be used once. If it wasn't you, ignore this message; your password stays the same."], cta: { label: "Choose a new password", url: v.url } }),
    es: (v) => ({ subject: "Restablece tu contraseña", lines: [`Hola ${v.name},`, "Alguien pidió restablecer la contraseña de tu cuenta. Toca el botón para elegir una nueva.", "Este enlace funciona por 1 hora y solo se puede usar una vez. Si no fuiste tú, ignora este mensaje; tu contraseña no cambia."], cta: { label: "Elegir una contraseña nueva", url: v.url } }) },

  "auth.reset_done": { transactional: true,
    en: (v) => ({ subject: "Your password was changed", lines: [`Hi ${v.name},`, "Your password was just changed and you were signed out everywhere. If this was you, no action is needed.", `If it wasn't you, reply to this email${v.support ? ` or write to ${v.support}` : ""} right away.`] }),
    es: (v) => ({ subject: "Tu contraseña fue cambiada", lines: [`Hola ${v.name},`, "Tu contraseña se cambió y se cerró tu sesión en todos los dispositivos. Si fuiste tú, no necesitas hacer nada.", `Si no fuiste tú, responde a este correo${v.support ? ` o escribe a ${v.support}` : ""} de inmediato.`] }) },

  "booking.requested.group": { transactional: true,
    en: (v) => ({ subject: `New booking request for ${longDate(v.date, "en")}`, lines: [`Hi ${v.name},`, `${v.customer} wants to book ${v.group} for a ${v.event} on ${longDate(v.date, "en")} at ${v.time} (${v.hours} hr, ${v.guests} guests) at ${v.address}.`, ...(v.addons ? [`Add-ons they ordered: ${v.addons}.`] : []), `They paid the ${v.deposit} deposit. After the platform fee you receive ${v.payout} now, and the customer pays you ${v.balance} at the event.`, "Please accept or decline soon so they can plan."], cta: { label: "Review the request", url: v.url }, sms: `${B}: new booking request for ${v.date} ${v.time}. Open your dashboard to accept: ${v.url}` }),
    es: (v) => ({ subject: `Nueva solicitud de reserva para el ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `${v.customer} quiere contratar a ${v.group} para su ${v.event} el ${longDate(v.date, "es")} a las ${v.time} (${v.hours} h, ${v.guests} invitados) en ${v.address}.`, ...(v.addons ? [`Extras que pidió: ${v.addons}.`] : []), `Pagó el depósito de ${v.deposit}. Después de la comisión de la plataforma recibes ${v.payout} ahora, y el cliente te paga ${v.balance} el día del evento.`, "Acepta o rechaza pronto para que puedan planear."], cta: { label: "Ver la solicitud", url: v.url }, sms: `${B}: nueva solicitud de reserva para ${v.date} ${v.time}. Abre tu panel para aceptar: ${v.url}` }) },

  "booking.received.customer": { transactional: true,
    en: (v) => ({ subject: `We got your request for ${v.group}`, lines: [`Hi ${v.name},`, `Your deposit of ${v.deposit} was received and ${v.group} has your request for ${longDate(v.date, "en")} at ${v.time}.`, `They will accept or decline soon. If they decline, your deposit is refunded in full. The balance of ${v.balance} is paid at the event.`, `Cancellation policy: ${v.policy}`], cta: { label: "See my booking", url: v.url } }),
    es: (v) => ({ subject: `Recibimos tu solicitud para ${v.group}`, lines: [`Hola ${v.name},`, `Recibimos tu depósito de ${v.deposit} y ${v.group} tiene tu solicitud para el ${longDate(v.date, "es")} a las ${v.time}.`, `Pronto aceptarán o rechazarán. Si rechazan, te devolvemos todo el depósito. El saldo de ${v.balance} se paga en el evento.`, `Política de cancelación: ${v.policy}`], cta: { label: "Ver mi reserva", url: v.url } }) },

  "booking.confirmed.customer": { transactional: true,
    en: (v) => ({ subject: `Confirmed: ${v.group} on ${longDate(v.date, "en")}`, lines: [`Hi ${v.name},`, `Great news: ${v.group} confirmed your ${v.event} on ${longDate(v.date, "en")} at ${v.time}.`, `Location: ${v.address}`, `Balance due: ${v.balance}. You can pay it in the app anytime before the event, or directly to the group.`, "Phone numbers can now be shared in your messages with the group."], cta: { label: "See my booking", url: v.url }, sms: `${B}: ${v.group} confirmed your booking for ${v.date} at ${v.time}.` }),
    es: (v) => ({ subject: `Confirmado: ${v.group} el ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `Buenas noticias: ${v.group} confirmó tu ${v.event} el ${longDate(v.date, "es")} a las ${v.time}.`, `Lugar: ${v.address}`, `Saldo pendiente: ${v.balance}. Puedes pagarlo en la app cuando quieras antes del evento, o directamente al grupo.`, "Ahora pueden compartir teléfonos en sus mensajes con el grupo."], cta: { label: "Ver mi reserva", url: v.url }, sms: `${B}: ${v.group} confirmó tu reserva para el ${v.date} a las ${v.time}.` }) },

  "booking.declined.customer": { transactional: true,
    en: (v) => ({ subject: `${v.group} can't take your ${longDate(v.date, "en")} booking`, lines: [`Hi ${v.name},`, `Unfortunately ${v.group} can't take your booking on ${longDate(v.date, "en")}. Your deposit of ${v.refund} is being refunded in full; it usually reaches your card in 5 to 10 business days.`, "Other groups may be free that day."], cta: { label: "Find another group", url: v.url }, sms: `${B}: ${v.group} can't take your ${v.date} booking. Your deposit is being refunded.` }),
    es: (v) => ({ subject: `${v.group} no puede tomar tu reserva del ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `Lamentablemente ${v.group} no puede tomar tu reserva del ${longDate(v.date, "es")}. Tu depósito de ${v.refund} se está reembolsando completo; normalmente llega a tu tarjeta en 5 a 10 días hábiles.`, "Otros grupos pueden estar libres ese día."], cta: { label: "Buscar otro grupo", url: v.url }, sms: `${B}: ${v.group} no puede tomar tu reserva del ${v.date}. Tu depósito se está reembolsando.` }) },

  "booking.cancelled.customer": { transactional: true,
    en: (v) => ({ subject: `${v.group} cancelled your ${longDate(v.date, "en")} booking`, lines: [`Hi ${v.name},`, `We're sorry: ${v.group} cancelled your booking on ${longDate(v.date, "en")}. Everything you paid (${v.refund}) is being refunded in full.`], cta: { label: "Find another group", url: v.url }, sms: `${B}: ${v.group} cancelled your ${v.date} booking. You are being refunded in full.` }),
    es: (v) => ({ subject: `${v.group} canceló tu reserva del ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `Lo sentimos: ${v.group} canceló tu reserva del ${longDate(v.date, "es")}. Todo lo que pagaste (${v.refund}) se está reembolsando completo.`], cta: { label: "Buscar otro grupo", url: v.url }, sms: `${B}: ${v.group} canceló tu reserva del ${v.date}. Te reembolsamos todo.` }) },

  "booking.cancelled.group": { transactional: true,
    en: (v) => ({ subject: `Booking cancelled by the customer: ${longDate(v.date, "en")}`, lines: [`Hi ${v.name},`, `${v.customer} cancelled the booking on ${longDate(v.date, "en")} at ${v.time}. Refund to the customer: ${v.refund}. That time is open again on your calendar.`], cta: { label: "Open my dashboard", url: v.url }, sms: `${B}: the ${v.date} ${v.time} booking was cancelled by the customer.` }),
    es: (v) => ({ subject: `Reserva cancelada por el cliente: ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `${v.customer} canceló la reserva del ${longDate(v.date, "es")} a las ${v.time}. Reembolso al cliente: ${v.refund}. Ese horario vuelve a estar libre en tu calendario.`], cta: { label: "Abrir mi panel", url: v.url }, sms: `${B}: el cliente canceló la reserva del ${v.date} ${v.time}.` }) },

  "balance.paid.customer": { transactional: true,
    en: (v) => ({ subject: `Balance paid for ${v.group}`, lines: [`Hi ${v.name},`, `We received your balance payment of ${v.balance} for ${v.group} on ${longDate(v.date, "en")}. Everything is paid: nothing to bring to the event!`], cta: { label: "See my booking", url: v.url } }),
    es: (v) => ({ subject: `Saldo pagado para ${v.group}`, lines: [`Hola ${v.name},`, `Recibimos tu pago del saldo de ${v.balance} para ${v.group} el ${longDate(v.date, "es")}. Todo está pagado: ¡no tienes que llevar nada al evento!`], cta: { label: "Ver mi reserva", url: v.url } }) },

  "balance.paid.group": { transactional: true,
    en: (v) => ({ subject: `Balance paid: ${v.customer}, ${longDate(v.date, "en")}`, lines: [`Hi ${v.name},`, `${v.customer} paid the ${v.balance} balance in the app for ${longDate(v.date, "en")}. It goes to your Stripe account, so there is nothing to collect at the event.`], cta: { label: "Open the booking", url: v.url }, sms: `${B}: ${v.customer} paid the ${v.balance} balance for ${v.date}. Nothing to collect at the event.` }),
    es: (v) => ({ subject: `Saldo pagado: ${v.customer}, ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `${v.customer} pagó el saldo de ${v.balance} en la app para el ${longDate(v.date, "es")}. Llega a tu cuenta de Stripe, así que no hay nada que cobrar en el evento.`], cta: { label: "Abrir la reserva", url: v.url }, sms: `${B}: ${v.customer} pagó el saldo de ${v.balance} del ${v.date}. No hay nada que cobrar en el evento.` }) },

  "resched.requested.group": { transactional: true,
    en: (v) => ({ subject: `Reschedule request: ${v.customer}`, lines: [`Hi ${v.name},`, `${v.customer} asks to move their ${v.event} from ${longDate(v.date, "en")} at ${v.time} to ${longDate(v.newDate, "en")} at ${v.newTime}.`, v.note ? `Their note: "${v.note}"` : "", "The new time is held for them until you answer. Nothing else changes: same price, same deposit."].filter(Boolean), cta: { label: "Answer the request", url: v.url }, sms: `${B}: ${v.customer} asks to move ${v.date} to ${v.newDate} ${v.newTime}. Answer in your dashboard: ${v.url}` }),
    es: (v) => ({ subject: `Solicitud de cambio de fecha: ${v.customer}`, lines: [`Hola ${v.name},`, `${v.customer} pide mover su ${v.event} del ${longDate(v.date, "es")} a las ${v.time} al ${longDate(v.newDate, "es")} a las ${v.newTime}.`, v.note ? `Su nota: "${v.note}"` : "", "El nuevo horario se guarda para ellos hasta que respondas. Nada más cambia: mismo precio, mismo depósito."].filter(Boolean), cta: { label: "Responder la solicitud", url: v.url }, sms: `${B}: ${v.customer} pide mover el ${v.date} al ${v.newDate} ${v.newTime}. Responde en tu panel: ${v.url}` }) },

  "resched.accepted.customer": { transactional: true,
    en: (v) => ({ subject: `New date confirmed: ${longDate(v.newDate, "en")}`, lines: [`Hi ${v.name},`, `${v.group} accepted your request. Your ${v.event} is now on ${longDate(v.newDate, "en")} at ${v.newTime}. Your deposit and price stay the same.`], cta: { label: "See my booking", url: v.url }, sms: `${B}: ${v.group} accepted the new date: ${v.newDate} at ${v.newTime}.` }),
    es: (v) => ({ subject: `Nueva fecha confirmada: ${longDate(v.newDate, "es")}`, lines: [`Hola ${v.name},`, `${v.group} aceptó tu solicitud. Tu ${v.event} ahora es el ${longDate(v.newDate, "es")} a las ${v.newTime}. Tu depósito y precio no cambian.`], cta: { label: "Ver mi reserva", url: v.url }, sms: `${B}: ${v.group} aceptó la nueva fecha: ${v.newDate} a las ${v.newTime}.` }) },

  "resched.declined.customer": { transactional: true,
    en: (v) => ({ subject: `${v.group} can't move your booking`, lines: [`Hi ${v.name},`, `${v.group} can't move your ${v.event} to ${longDate(v.newDate, "en")}. Your booking stays on ${longDate(v.date, "en")} at ${v.time}.`, "You can message the group to find another date, or cancel under your policy."], cta: { label: "See my booking", url: v.url }, sms: `${B}: ${v.group} can't move your booking. It stays on ${v.date} at ${v.time}.` }),
    es: (v) => ({ subject: `${v.group} no puede mover tu reserva`, lines: [`Hola ${v.name},`, `${v.group} no puede mover tu ${v.event} al ${longDate(v.newDate, "es")}. Tu reserva sigue el ${longDate(v.date, "es")} a las ${v.time}.`, "Puedes escribirle al grupo para buscar otra fecha, o cancelar según tu política."], cta: { label: "Ver mi reserva", url: v.url }, sms: `${B}: ${v.group} no puede mover tu reserva. Sigue el ${v.date} a las ${v.time}.` }) },

  "offer.customer": { transactional: true,
    en: (v) => ({ subject: `${v.group} sent you a custom offer`, lines: [`Hi ${v.name},`, `${v.group} made you a custom offer: ${v.offer}, ${v.hours} hr for ${v.price}.`, v.note ? `Their note: "${v.note}"` : "", `It's waiting on the group's page under "Custom offer" for the next ${v.days} days. Pick your date and book it to secure the price.`].filter(Boolean), cta: { label: "See the offer", url: v.url }, sms: `${B}: ${v.group} sent you a custom offer (${v.price}). See it: ${v.url}` }),
    es: (v) => ({ subject: `${v.group} te envió una oferta personalizada`, lines: [`Hola ${v.name},`, `${v.group} te hizo una oferta personalizada: ${v.offer}, ${v.hours} h por ${v.price}.`, v.note ? `Su nota: "${v.note}"` : "", `Está en la página del grupo como "Oferta personalizada" por ${v.days} días. Elige tu fecha y resérvala para asegurar el precio.`].filter(Boolean), cta: { label: "Ver la oferta", url: v.url }, sms: `${B}: ${v.group} te envió una oferta personalizada (${v.price}). Velá: ${v.url}` }) },

  "request.expanded.customer": {
    en: (v) => ({ subject: `We sent your ${v.event} request to ${v.n} more group${v.n === "1" ? "" : "s"}`, lines: [`Hi ${v.name},`, `No group had answered your ${v.event} request for ${longDate(v.date, "en")} after a day, so we sent it to ${v.n} more group${v.n === "1" ? "" : "s"} that are free that day. Replies and offers show up on your quotes page.`], cta: { label: "See my quotes", url: v.url }, sms: `${B}: nobody had answered yet, so we sent your request to ${v.n} more group${v.n === "1" ? "" : "s"}. ${v.url}` }),
    es: (v) => ({ subject: `Enviamos tu solicitud de ${v.event} a ${v.n} grupo${v.n === "1" ? "" : "s"} más`, lines: [`Hola ${v.name},`, `Ningún grupo había respondido tu solicitud de ${v.event} para el ${longDate(v.date, "es")} después de un día, así que la enviamos a ${v.n} grupo${v.n === "1" ? "" : "s"} más que están libres ese día. Las respuestas y ofertas aparecen en tu página de cotizaciones.`], cta: { label: "Ver mis cotizaciones", url: v.url }, sms: `${B}: nadie había respondido, así que enviamos tu solicitud a ${v.n} grupo${v.n === "1" ? "" : "s"} más. ${v.url}` }) },

  "request.group": {
    en: (v) => ({ subject: `A family needs music: ${v.event} on ${longDate(v.date, "en")}`, lines: [`Hi ${v.name},`, `A customer is asking ${v.group} for a price for a ${v.event} on ${longDate(v.date, "en")}, about ${v.guests} guests. You're free that day, so we sent it to you and just a few other groups.`, `It costs you nothing to answer. Reply in the chat, or send a private custom offer they can book in one tap. Fast answers win these.`], cta: { label: "Answer the request", url: v.url }, sms: `${B}: a family asked ${v.group} for a price for ${v.date}. Answer fast: ${v.url}` }),
    es: (v) => ({ subject: `Una familia necesita música: ${v.event} el ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `Un cliente le pide un precio a ${v.group} para su ${v.event} el ${longDate(v.date, "es")}, unas ${v.guests} personas. Estás libre ese día, por eso te lo enviamos a ti y a unos pocos grupos más.`, `No cuesta nada responder. Contesta en el chat, o envía una oferta personalizada privada que puedan reservar con un toque. Los que responden rápido ganan.`], cta: { label: "Responder la solicitud", url: v.url }, sms: `${B}: una familia le pidió precio a ${v.group} para el ${v.date}. Responde rápido: ${v.url}` }) },

  "message.group": {
    en: (v) => ({ subject: `New message about ${v.group}`, lines: [`Hi ${v.name},`, `You have a new message from a customer about ${v.group}. Reply in the app to keep the conversation moving.`], cta: { label: "Open messages", url: v.url }, sms: `${B}: new message about ${v.group}. Reply in the app: ${v.url}` }),
    es: (v) => ({ subject: `Nuevo mensaje sobre ${v.group}`, lines: [`Hola ${v.name},`, `Tienes un mensaje nuevo de un cliente sobre ${v.group}. Responde en la app para no perder la conversación.`], cta: { label: "Abrir mensajes", url: v.url }, sms: `${B}: nuevo mensaje sobre ${v.group}. Responde en la app: ${v.url}` }) },

  "message.customer": {
    en: (v) => ({ subject: `${v.group} replied to your message`, lines: [`Hi ${v.name},`, `${v.group} answered your message. Open the app to read it.`], cta: { label: "Read the reply", url: v.url }, sms: `${B}: ${v.group} replied to your message. Open the app to read it: ${v.url}` }),
    es: (v) => ({ subject: `${v.group} respondió a tu mensaje`, lines: [`Hola ${v.name},`, `${v.group} contestó tu mensaje. Abre la app para leerlo.`], cta: { label: "Leer la respuesta", url: v.url }, sms: `${B}: ${v.group} respondió a tu mensaje. Ábrelo en la app: ${v.url}` }) },

  "checkin.customer": { transactional: true,
    en: (v) => ({ subject: `${v.group} checked in`, lines: [`Hi ${v.name},`, `${v.group} checked in for your ${v.event} today (${longDate(v.date, "en")}). Enjoy the music!`, `Afterwards, a quick review helps other families choose.`], cta: { label: "Open my bookings", url: v.url }, sms: `${B}: ${v.group} has arrived for your event today. Enjoy!` }),
    es: (v) => ({ subject: `${v.group} ya llegó`, lines: [`Hola ${v.name},`, `${v.group} registró su llegada a tu ${v.event} de hoy (${longDate(v.date, "es")}). ¡Disfruta la música!`, `Después, una reseña rápida ayuda a otras familias a elegir.`], cta: { label: "Abrir mis reservas", url: v.url }, sms: `${B}: ${v.group} ya llegó a tu evento de hoy. ¡Disfruta!` }) },

  "noshow.reported.group": { transactional: true,
    en: (v) => ({ subject: `A customer says you didn't arrive on ${longDate(v.date, "en")}`, lines: [`Hi ${v.name},`, `${v.customer} reported that ${v.group} did not show up to the ${v.event} on ${longDate(v.date, "en")}, and nobody checked in with the arrival code.`, `If that's a mistake, tell us your side in your dashboard within 3 days. We review every report by hand before any refund.`], cta: { label: "Answer the report", url: v.url }, sms: `${B}: a customer reported a no-show for ${v.date}. If that's wrong, answer in your dashboard: ${v.url}` }),
    es: (v) => ({ subject: `Un cliente dice que no llegaron el ${longDate(v.date, "es")}`, lines: [`Hola ${v.name},`, `${v.customer} reportó que ${v.group} no llegó a su ${v.event} del ${longDate(v.date, "es")}, y nadie registró la llegada con el código.`, `Si es un error, cuéntanos tu versión en tu panel dentro de 3 días. Revisamos cada reporte a mano antes de cualquier reembolso.`], cta: { label: "Responder al reporte", url: v.url }, sms: `${B}: un cliente reportó que no llegaron el ${v.date}. Si es un error, responde en tu panel: ${v.url}` }) },

  "noshow.refunded.customer": { transactional: true,
    en: (v) => ({ subject: `We're refunding you ${v.refund}`, lines: [`Hi ${v.name},`, `We're sorry ${v.group} didn't show up on ${longDate(v.date, "en")}. We reviewed your report and are refunding ${v.refund}, everything you paid in the app.`, `It can take a few business days to appear on your card.`], cta: { label: "Open my bookings", url: v.url }, sms: `${B}: we're sorry ${v.group} didn't show. We're refunding ${v.refund}.` }),
    es: (v) => ({ subject: `Te reembolsamos ${v.refund}`, lines: [`Hola ${v.name},`, `Lamentamos que ${v.group} no llegara el ${longDate(v.date, "es")}. Revisamos tu reporte y te reembolsamos ${v.refund}, todo lo que pagaste en la app.`, `Puede tardar unos días hábiles en aparecer en tu tarjeta.`], cta: { label: "Abrir mis reservas", url: v.url }, sms: `${B}: lamentamos que ${v.group} no llegara. Te reembolsamos ${v.refund}.` }) },

  "noshow.rejected.customer": { transactional: true,
    en: (v) => ({ subject: `About your report for ${v.group}`, lines: [`Hi ${v.name},`, `We reviewed your no-show report for ${v.group} on ${longDate(v.date, "en")} and could not confirm it, so no refund was issued.`, `If you think this is wrong, reply to this email with details and we'll look again.`], cta: { label: "Open my bookings", url: v.url } }),
    es: (v) => ({ subject: `Sobre tu reporte de ${v.group}`, lines: [`Hola ${v.name},`, `Revisamos tu reporte de que ${v.group} no llegó el ${longDate(v.date, "es")} y no pudimos confirmarlo, así que no se hizo un reembolso.`, `Si crees que es un error, responde a este correo con los detalles y lo revisamos de nuevo.`], cta: { label: "Abrir mis reservas", url: v.url } }) },

  "review.reminder": {
    en: (v) => ({ subject: `How was ${v.group}?`, lines: [`Hi ${v.name},`, `We hope ${v.group} made your event special. A quick review helps other families choose, and it means a lot to the group.`], cta: { label: "Leave a review", url: v.url }, sms: `${B}: how was ${v.group}? Leave a quick review: ${v.url}` }),
    es: (v) => ({ subject: `¿Cómo estuvo ${v.group}?`, lines: [`Hola ${v.name},`, `Esperamos que ${v.group} haya hecho especial tu evento. Una reseña rápida ayuda a otras familias a elegir y significa mucho para el grupo.`], cta: { label: "Dejar una reseña", url: v.url }, sms: `${B}: ¿cómo estuvo ${v.group}? Deja una reseña rápida: ${v.url}` }) },

  "event.reminder.customer": { transactional: true,
    en: (v) => ({ subject: `${v.when === "tomorrow" ? "Tomorrow" : "In a week"}: ${v.group} at your ${v.event}`, lines: [`Hi ${v.name},`, `A reminder that ${v.group} plays at your ${v.event} ${v.when === "tomorrow" ? "tomorrow" : "in 7 days"}: ${longDate(v.date, "en")} at ${v.time}, ${v.address}.`, v.balanceDue ? `Balance still due: ${v.balanceDue}. Pay it in the app or directly to the group.` : "Your balance is paid. Nothing else to do!"], cta: { label: "See my booking", url: v.url }, sms: `${B}: reminder, ${v.group} plays ${v.when === "tomorrow" ? "tomorrow" : "in 7 days"} (${v.date} ${v.time}).${v.balanceDue ? ` Balance due ${v.balanceDue}.` : ""}` }),
    es: (v) => ({ subject: `${v.when === "tomorrow" ? "Mañana" : "En una semana"}: ${v.group} en tu ${v.event}`, lines: [`Hola ${v.name},`, `Te recordamos que ${v.group} toca en tu ${v.event} ${v.when === "tomorrow" ? "mañana" : "en 7 días"}: ${longDate(v.date, "es")} a las ${v.time}, ${v.address}.`, v.balanceDue ? `Saldo pendiente: ${v.balanceDue}. Págalo en la app o directamente al grupo.` : "Tu saldo está pagado. ¡No falta nada!"], cta: { label: "Ver mi reserva", url: v.url }, sms: `${B}: recordatorio, ${v.group} toca ${v.when === "tomorrow" ? "mañana" : "en 7 días"} (${v.date} ${v.time}).${v.balanceDue ? ` Saldo pendiente ${v.balanceDue}.` : ""}` }) },

  "event.reminder.group": { transactional: true,
    en: (v) => ({ subject: `Tomorrow: ${v.event} for ${v.customer}`, lines: [`Hi ${v.name},`, `Tomorrow you play a ${v.event} for ${v.customer}: ${longDate(v.date, "en")} at ${v.time}, ${v.address}, about ${v.guests} guests.`, v.phone ? `Customer phone: ${v.phone}` : "", v.balanceLine].filter(Boolean), cta: { label: "Open the booking", url: v.url }, sms: `${B}: tomorrow ${v.date} ${v.time}, ${v.event} for ${v.customer}.` }),
    es: (v) => ({ subject: `Mañana: ${v.event} de ${v.customer}`, lines: [`Hola ${v.name},`, `Mañana tocas en el evento de ${v.customer} (${v.event}): ${longDate(v.date, "es")} a las ${v.time}, ${v.address}, unos ${v.guests} invitados.`, v.phone ? `Teléfono del cliente: ${v.phone}` : "", v.balanceLine].filter(Boolean), cta: { label: "Abrir la reserva", url: v.url }, sms: `${B}: mañana ${v.date} ${v.time}, ${v.event} de ${v.customer}.` }) },

  "waitlist.joined": { transactional: true,
    en: (v) => ({ subject: `You're on the list for ${v.city}`, lines: ["Thanks for your interest!", `${B} is launching in Chicago first. We'll email you once we have groups near ${v.city}.`], cta: { label: "See groups in Chicago", url: v.url } }),
    es: (v) => ({ subject: `Estás en la lista para ${v.city}`, lines: ["¡Gracias por tu interés!", `${B} empieza en Chicago. Te escribiremos cuando tengamos grupos cerca de ${v.city}.`], cta: { label: "Ver grupos en Chicago", url: v.url } }) }
};

// Adds a template at runtime (used by feature modules so this file doesn't need to know about every feature).
export function defineTemplates(more) { Object.assign(TEMPLATES, more); }

export function renderEmail({ subject, lines, cta }, { lang, config, unsubUrl }) {
  const footerBits = [config.businessName, config.businessAddress, config.supportEmail].filter(Boolean).join(" · ");
  const unsubText = unsubUrl ? (lang === "es" ? `Dejar de recibir estos avisos: ${unsubUrl}` : `Stop these notifications: ${unsubUrl}`) : "";
  const text = [...lines, cta ? `${cta.label}: ${cta.url}` : "", "", "—", footerBits, unsubText].filter((x, i, a) => x !== "" || (i > 0 && a[i - 1] !== "")).join("\n");
  const button = cta ? `<p style="margin:22px 0"><a href="${h(cta.url)}" style="background:#1f5fd6;color:#ffffff;text-decoration:none;font-weight:700;padding:12px 20px;border-radius:10px;display:inline-block">${h(cta.label)}</a></p>` : "";
  const html = `<div style="background:#eef2f8;padding:24px 12px;font-family:Arial,Helvetica,sans-serif;color:#101828"><div style="max-width:540px;margin:0 auto;background:#ffffff;border:1px solid #d3dae6;border-radius:12px;overflow:hidden">
    <div style="background:#0a1022;padding:16px 22px;color:#7fb0ff;font-family:Georgia,serif;font-size:22px">${h(config.businessName)}</div>
    <div style="padding:22px"><h1 style="font-size:19px;margin:0 0 14px;font-family:Georgia,serif">${h(subject)}</h1>${lines.map((l) => `<p style="margin:0 0 12px;line-height:1.5">${h(l)}</p>`).join("")}${button}</div>
    <div style="padding:14px 22px;font-size:12px;color:#4a5568;border-top:1px solid #d3dae6">${h(footerBits)}${unsubUrl ? `<br><a href="${h(unsubUrl)}" style="color:#4a5568">${h(lang === "es" ? "Dejar de recibir estos avisos" : "Stop these notifications")}</a>` : ""}</div></div></div>`;
  return { subject, text, html };
}
