// Writes docs/spanish-review.md: every screen string and every email/text, English next to Spanish, so a native speaker can read
// and correct them in one sitting. Regenerate with `npm run spanish-sheet`. Also lists strings that are identical in both languages.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DICT } from "../public/js/i18n.js";
import { TEMPLATES, eventLabel } from "./emails.js";

const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../docs/spanish-review.md");
const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const SAMPLE = { name: "Ana", group: "Mariachi Tierra Viva", customer: "Carlos", event: "Wedding", date: "2026-11-07", newDate: "2026-11-14", time: "2:00 PM", newTime: "4:00 PM", address: "Casa Blanca Hall, Chicago", total: "$600", deposit: "$150", balance: "$450", payout: "$90", refund: "$150", price: "$900", offer: "Paquete quinceañera", hours: "3", days: "7", note: "Con sonido incluido", guests: "120", n: "2", url: "https://tu-sitio.example/#/ruta", city: "Chicago, IL", amount: "$450", when: "tomorrow", phone: "(312) 555-0142", support: "ayuda@tu-sitio.example", balanceDue: "$450", balanceLine: "Balance to collect: $450", policyKey: "moderate", market: "Chicago" };
// The program turns the event type into the reader's language before filling a template, so the sheet does the same.
const varsFor = (lang) => { const v = { ...SAMPLE, event: eventLabel(SAMPLE.event, lang) }; return new Proxy(v, { get: (t, k) => (k in t ? t[k] : `[${String(k)}]`) }); };

const keys = Object.keys(DICT.en);
const missing = keys.filter((k) => !(k in DICT.es));
const same = keys.filter((k) => DICT.es[k] === DICT.en[k] && /[a-záéíóúñ]{4,}/i.test(DICT.en[k]) && !/^(WhatsApp|ES|EN)$/.test(DICT.en[k]));

let md = `# Spanish review sheet

Generated by \`npm run spanish-sheet\` (do not edit by hand: change the strings in \`public/js/i18n.js\` / \`public/js/i18n-new.js\` / \`server/emails.js\` and regenerate).

**How to use it:** read the Spanish column. It should sound like a Mexican-American family or a working musician talking, not like a translation.
Mark anything stiff, wrong or too formal, and write the better version next to it. The site speaks to people as **tú**. Words in {braces} are filled in by the program: keep them exactly.

- Screen strings: ${keys.length}
- Strings missing a Spanish version: ${missing.length}${missing.length ? " (" + missing.join(", ") + ")" : ""}
- Strings identical in both languages (check these are meant to be): ${same.length}

## Same in both languages (check)

${same.length ? same.map((k) => `- \`${k}\`: ${cell(DICT.en[k])}`).join("\n") : "None."}

## Emails and texts

Names, dates and amounts below are sample values.

`;
for (const [kind, tpl] of Object.entries(TEMPLATES)) {
  md += `### \`${kind}\`\n\n`;
  for (const lang of ["en", "es"]) {
    try {
      const m = tpl[lang](varsFor(lang));
      md += `**${lang === "es" ? "Español" : "English"}**\n\n- Subject: ${m.subject}\n${(m.lines || []).map((l) => `- ${l}`).join("\n")}\n${m.cta ? `- Button: ${m.cta.label}\n` : ""}${m.sms ? `- Text message: ${m.sms}\n` : ""}\n`;
    } catch (e) { md += `**${lang}**: could not render a sample (${e.message})\n\n`; }
  }
}
md += `## Screen text\n\n| Key | English | Español |\n| --- | --- | --- |\n${keys.map((k) => `| \`${k}\` | ${cell(DICT.en[k])} | ${cell(DICT.es[k])} |`).join("\n")}\n`;
fs.writeFileSync(out, md);
console.log(`Wrote ${path.relative(process.cwd(), out)}: ${keys.length} screen strings, ${Object.keys(TEMPLATES).length} email templates, ${same.length} identical in both languages, ${missing.length} missing in Spanish.`);
